import Head from "next/head";
import Image from "next/image";
import SearchBar from "../components/SearchBar";
import CoinList from "../components/CoinList";
import Layout from "../components/Layout";

export default function Home({ data }) {
  console.log(data);
  return (
    <Layout>
      <Head>
        <title>Crypto Finance Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SearchBar />
      <CoinList data={data} />
    </Layout>
  );
}

export const getServerSideProps = async () => {
  const res = await fetch(
    "https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=10&page=1&sparkline=false"
  );

  const data = await res.json();

  return {
    props: {
      data,
    },
  };
};
